apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - path: imageupdateautomation.yaml
    target:
      group: image.toolkit.fluxcd.io
      version: v1
      kind: ImageUpdateAutomation
