apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
configurations:
- nameReference.yaml
patches:
  - path: patch-ocirepository.yaml
    target:
      group: source.toolkit.fluxcd.io
      version: v1
      kind: OCIRepository
