apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: unimportant
spec:
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
