apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: ocirepository # not important, this patch should be used with labelSelector and annotationSelector
  annotations:
    kustomize-applied-patch/pull-secret: global
spec:
  secretRef:
    name: global-pull-secret
